#!/bin/sh
#
# Run the socketcan1 daemon
#

DAEMON="socketcan1"
PIDFILE="/var/run/$DAEMON.pid"


start() {
	echo -n "Starting $DAEMON... "
	start-stop-daemon -S -b -m -p $PIDFILE -x /usr/bin/socketcand -- -i can1 -p 10001 -l eth1
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

stop() {
	echo -n "Stopping $DAEMON... "
	start-stop-daemon -K -p $PIDFILE
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?